### PR TITLE
Refactor gateway logics

### LINKED ISSUE #299: Do not send flip request after adding flip rule in robot
I tried to do delivery service, repeatedly.
In normal case, robot showed following log .

```
[INFO] [WallTime: 1433157913.826239] Rapp Manager : dwleeab69e6702d26418eb6018116a9366941
[INFO] [WallTime: 1433157914.331153] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/map,subscriber)]
[INFO] [WallTime: 1433157914.331749] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/map_metadata,subscriber)]
[INFO] [WallTime: 1433157914.332177] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/annotation/tables,subscriber)]
[INFO] [WallTime: 1433157914.332540] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/annotation/ar_markers,subscriber)]
[INFO] [WallTime: 1433157914.332903] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/annotation/viz_tables,subscriber)]
[INFO] [WallTime: 1433157914.334867] Rapp Manager : successfully flipped ['map', 'map_metadata', 'tables', 'ar_markers', 'viz_tables']
[INFO] [WallTime: 1433157914.337892] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/young/robot_pose,publisher)]
[INFO] [WallTime: 1433157914.338520] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/young/robot_status,publisher)]
[INFO] [WallTime: 1433157914.340588] Rapp Manager : successfully flipped ['robot_pose', 'robot_status']
[INFO] [WallTime: 1433157914.344462] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/delivery_order_0771d9df6c4641f7a8c6c36556765ef6,action_server)]
[INFO] [WallTime: 1433157914.347544] Rapp Manager : successfully flipped ['delivery_order_0771d9df6c4641f7a8c6c36556765ef6']
[INFO] [WallTime: 1433157917.904285] Gateway : sending flip request [dwleeab69e6702d26418eb6018116a9366941][subscriber][/map][/young/amcl]
[INFO] [WallTime: 1433157918.123079] Gateway : sending flip request [dwleeab69e6702d26418eb6018116a9366941][subscriber][/annotation/ar_markers][/young/tracker_manager]
[INFO] [WallTime: 1433157918.261181] Gateway : sending flip request [dwleeab69e6702d26418eb6018116a9366941][subscriber][/annotation/ar_markers][/young/docking_interactor]
[INFO] [WallTime: 1433157918.405498] Gateway : sending flip request [dwleeab69e6702d26418eb6018116a9366941][publisher][/young/robot_status][/young/office_waiterbot_state_manager]
[INFO] [WallTime: 1433157918.532766] Gateway : sending flip request [dwleeab69e6702d26418eb6018116a9366941][publisher][/young/robot_pose][/young/robot_pose_publisher]

```

In above log, concert client sends flip request as soon as adding flip rule. 
However, it did not occasionally send flip request after adding flip rule like following log.

```
process[young/robot_pose_publisher-57]: started with pid [743]
[INFO] [WallTime: 1433158092.529331] Rapp Manager : dwleeab69e6702d26418eb6018116a9366941
[INFO] [WallTime: 1433158093.033828] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/map,subscriber)]
[INFO] [WallTime: 1433158093.034495] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/map_metadata,subscriber)]
[INFO] [WallTime: 1433158093.034905] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/annotation/tables,subscriber)]
[INFO] [WallTime: 1433158093.035358] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/annotation/ar_markers,subscriber)]
[INFO] [WallTime: 1433158093.035804] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/annotation/viz_tables,subscriber)]
[INFO] [WallTime: 1433158093.039067] Rapp Manager : successfully flipped ['map', 'map_metadata', 'tables', 'ar_markers', 'viz_tables']
[INFO] [WallTime: 1433158093.042436] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/young/robot_pose,publisher)]
[INFO] [WallTime: 1433158093.042919] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/young/robot_status,publisher)]
[INFO] [WallTime: 1433158093.044773] Rapp Manager : successfully flipped ['robot_pose', 'robot_status']
[INFO] [WallTime: 1433158093.048382] Gateway : added flip rule [dwleeab69e6702d26418eb6018116a9366941:(/delivery_order_6fb58c0fe30245e1bfbddb14ac58c077,action_server)]
[INFO] [WallTime: 1433158093.051253] Rapp Manager : successfully flipped ['delivery_order_6fb58c0fe30245e1bfbddb14ac58c077']

[ INFO] [1433158107.443481595]: Zeroconf: resolved service [xavier][_ros-multimaster-hub._tcp][local][3][ipv4][192.168.10.32:6380]

[INFO] [WallTime: 1433158116.938716] Gateway : sending unflip request [dwleeab69e6702d26418eb6018116a9366941][subscriber][/annotation/tables][/young/semantic_navigator]
[INFO] [WallTime: 1433158117.911817] Gateway : sending unflip request [dwleeab69e6702d26418eb6018116a9366941][action_server][/delivery_order_0771d9df6c4641f7a8c6c36556765ef6][/young/office_waiterbot_state_manager]
```

I will follow this issue and describe the more detail situation. 

Note that this error case was when waiterbot received second order from the service. So it is adding flip request for second delivery action [delivery_order_**6fb58**c0fe30245e1bfbddb14ac58c077] and trying to unflip [delivery_order_**0771d**9df6c4641f7a8c6c36556765ef6] which is the first delivery action

### PR DESCRIPTION
**Pull request by jihoonl**
It fixes #299.

Tested and working fine.

### CODE REVIEW

**Comment by jihoonl** [comment]
@stonier @piyushk Please review

**Comment by dwlee** [comment]
When `stop rapp` is called, following error is happened at waiterbot and master side.

I do not set network latency. 

**waiterbot**

```
[INFO] [WallTime: 1434359750.286143] Rapp Manager : Stopping rapp 'waiterbot_rapps/pickup_delivery'.
waiterbot_rapps/pickup_delivery
[young/robot_pose_publisher-19] killing on exit
[young/dock_drive-18] killing on exit
[ INFO] [1434359750.374805985]: Unloading nodelet /young/dock_drive from manager /mobile_base_nodelet_manager
[young/docking_interactor-17] killing on exit
[young/move_base-16] killing on exit
[young/navigation_velocity_smoother-15] killing on exit
[young/semantic_navigator-14] killing on exit
[young/amcl-13] killing on exit
[young/localization_manager-12] killing on exit
[ INFO] [1434359750.384557000]: Unloading nodelet /young/navigation_velocity_smoother from manager /mobile_base_nodelet_manager
[young/tracker_manager-11] killing on exit
[young/ar_pair_tracking-10] killing on exit
Traceback (most recent call last):
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 81, in spin
    self._gateway.spin()
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 78, in spin
    self.watcher_thread.start()
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 75, in start
    self._gateway.update_flipped_interface(connections, remote_gateway_hub_index)
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 146, in update_flipped_interface
    local_connection_index, remote_gateway_hub_index, self._unique_name, self.master)
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/flipped_interface.py", line 93, in update
    new_flips, removed_flips, flipped = self._prepare_flips(connections, remote_gateways, unique_name, master)  # Totally regenerate a new flipped interface, compare with old
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/flipped_interface.py", line 256, in _prepare_flips
    matched_flip_rules = self._generate_flips(connection.rule.type, connection.rule.name, connection.rule.node, remote_gateways, unique_name, master)
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/flipped_interface.py", line 237, in _generate_flips
    matched_flip.rule.node = "%s,%s"%(node, master.lookupNode(node)) # just in case we used a regex
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 433, in lookupNode
    return self._succeed(self.handle.lookupNode(self.caller_id, node_name))        
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 154, in _succeed
    raise Error(msg)
rosgraph.masterapi.MasterError: unknown node [/young/tracker_manager]
[young/ar_track_alvar-9] killing on exit
[young/office_waiterbot_state_manager-8] killing on exit
[ INFO] [1434359750.795600175]: Stopping depth stream.
[INFO] [WallTime: 1434359750.799641] TrackerManager : Bye Bye
[young/ir_to_laserscan-6] killing on exit
[young/ir_link_publisher-5] killing on exit
[young/depthimage_to_laserscan-4] killing on exit
[ INFO] [1434359750.890868253]: Unloading nodelet /young/depthimage_to_laserscan from manager camera/camera_nodelet_manager
[INFO] [WallTime: 1434359750.987352] Localization Manager : Bye Bye
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
[young/camera/rectify_color-3] killing on exit
[ INFO] [1434359751.086928824]: Unloading nodelet /young/camera/rectify_color from manager camera_nodelet_manager
[young/camera/driver-2] killing on exit
[ INFO] [1434359751.092420465]: Unloading nodelet /young/camera/driver from manager camera_nodelet_manager
[young/camera/camera_nodelet_manager-1] killing on exit
[INFO] [WallTime: 1434359751.431864] Robot State Manager : Bye Bye
[INFO] [WallTime: 1434359752.884904] Rapp Manager : stopped rapp [waiterbot_rapps/pickup_delivery]'.

```

**Master**

```
[WARN] [WallTime: 1434359821.227075] Hub Watcher: gateway young137456f6ae764c958ecb3cea7866f419 has been unavailable for 60 seconds! Marking as unavailable.
[INFO] [WallTime: 1434359822.148881] Conductor : concert client transition [available->missing][young]
```

**Comment by jihoonl** [comment]
The last commit should catch the exception

**Comment by jihoonl** [comment]
Tested enough and confirmed that it works fine.

**Pull request merged**
