### PR TITLE
flips without pubsubs

### PR DESCRIPTION
**Pull request by piyushk**
This PR introduces the following changes
- Flips no longer use pubsubs, but are written in the database. This makes it easier to synchronize flips in intermittent wireless. Furthermore, these flips are encrypted using basic RSA encryption.
- The gateway hub interface no longer blocks listening on a channel.
- Basic RSA encryption/decryption in utils
- Serialization has been switched from json to CPickle, to remove any unicode to string conversion problems. This makes entries in redis slightly less readable.
- There is now an initial lag while flipping, dependent on the watcher thread time period.

Tested using the following script:

```
rocon_launch rocon_gateway_tests singlehub.concert
```

### CODE REVIEW

**Comment by piyushk** [comment]
Hold off on this for now. I'm pretty sure this pr will break flipping across a multihub scenario.

**Comment by piyushk** [comment]
I think i've gottten the multihub issues resolved. Merge after https://github.com/robotics-in-concert/rocon_msgs/pull/83

**Comment by piyushk** [comment]
Alright. I'm finally done with this. A code review is probably necessary.

**Comment by stonier** [comment]
Hard to find any problems in here, looks mostly very good. I ran it through the few rocon gateway tests we have and also on the concert tutorials without a problem. The only oddity I could detect was the following output at the end of a `rocon_test rocon_gateway_tests flips.test --screen` (note the ERROR logs in particular):

```
[INFO] [WallTime: 1395134256.522267] Gateway : unregistered from the hub [Undiscovered Hub]
[INFO] [WallTime: 1395134256.522870] Gateway : unregistered from the hub [Secondary Hub]
Got SIGINT, quitting.
Got SIGINT, quitting.
[ INFO] [1395134258.258710859]: Zeroconf: service was removed [Primary Hub][_ros-multimaster-hub._tcp][local][2][ipv4]
[ERROR] [WallTime: 1395134258.602192] Gateway: Unable to update network interface information
[ERROR] [WallTime: 1395134258.603338] Gateway: Unable to update network interface information
[ INFO] [1395134258.818438514]: Zeroconf: service was removed [Secondary Hub][_ros-multimaster-hub._tcp][local][2][ipv4]
[INFO] [WallTime: 1395134259.167801] Gateway : shutting down.
[INFO] [WallTime: 1395134259.168214] Gateway : unregistered from the hub [Undiscovered Hub]
[INFO] [WallTime: 1395134259.168546] Gateway : unregistered from the hub [Secondary Hub]
[INFO] [WallTime: 1395134259.168885] Gateway : unregistered from the hub [Primary Hub]
testtest_flips ... ok
[ROSTEST]-----------------------------------------------------------------------

[rocon_gateway_tests.rosunit-test_flips/test_flip_all][passed]
[rocon_gateway_tests.rosunit-test_flips/test_flip_regex_tutorials][passed]
[rocon_gateway_tests.rosunit-test_flips/test_flip_tutorials][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 3
 * ERRORS: 0
 * FAILURES: 0
```

Those errors are new - never saw them with the old beast (or maybe rarely got to see them). I'm getting them about 80% now. It is popping up in the watcher thread loop:

```
        while not rospy.is_shutdown():
            # don't waste time processing if we're not connected to at least one hub
            if self._gateway.is_connected():
                try:
                    connections = self._master.get_connection_state()
                except httplib.ResponseNotReady:
                    rospy.logwarn("Gateway : received 'ResponseNotReady' from master api")
                    self._sleep()
                    continue
                remote_gateway_hub_index = self._hub_manager.create_remote_gateway_hub_index()
                self._gateway.update_network_information()
                self._gateway.update_flipped_interface(connections, remote_gateway_hub_index)
                self._gateway.update_public_interface(connections)
                self._gateway.update_pulled_interface(connections, remote_gateway_hub_index)
                registrations = self._hub_manager.get_flip_requests()
                self._gateway.update_flipped_in_interface(registrations, remote_gateway_hub_index)
            self._sleep()
```

which means it's triggering shutdown very early in the loop and almost never in the sleep. These tests are designed with only an interval of 2. Increasing that to 5 does indeed almost eliminate the messages.

Conclusion - I think we can ignore this, it's not significant and more likely just due to the sequence of events and timings in the rocon test.

**Comment by stonier** [comment]
> There is now an initial lag while flipping, dependent on the watcher thread time period.

This is probably not a big issue. This watcher loop also creates latencies for other flows as well. A common pattern with usage of this watcher loop is that you want it to be low latency when things are happening and really slow when nothing is happening. Late last year I put in a ros service for this, so external components can tune it in runtime, in `gateway_node.py`:

```
gateway_services['set_watcher_period']  = rospy.Service('~set_watcher_period',  gateway_srvs.SetWatcherPeriod, self._gateway.ros_service_set_watcher_period)
```

The rocon app manager I think uses this service to be responsive upon starting an app and then cranks it down once it's running. Until we come up with a better solution that seems to be enough to reduce crankiness in us users :)

**Comment by stonier** [comment]
Going to merge this as I can't pick up any obvious problems - I'd like to get this into the hands of the other guys here who will undoubtedly find a thing or two wrong with it while developing.

**Comment by piyushk** [comment]
@stonier I was using flips.test to test this PR until I realized that it was not working correctly. It just makes sure that the sender successfully flipped, but not that the flip is accepted at the receiving side. From what I understand, it was doing the same thing when we were using pub/sub for flip, i.e. it does not test flip-ins. Can you confirm this?

In https://github.com/robotics-in-concert/rocon_multimaster/issues/255, I plan to start checking that flips were accepted in flips.test

**Comment by stonier** [comment]
Absolutely correct and good catch. I really like the status updates - it's an issue I've been aware of for a long time, we did no checking whatsoever with the pubsub mechanism, so it was impossible to know if the flip had been firewalled or not. With a response this opens up ways of enabling a user to make decisions about what to do depending on whether or not a flip has worked or not.

I have an old issue open for tackling this topic: #102

**Comment by piyushk** [comment]
What's the easiest way to change the interval between tests? Something doesn't work quite right if I try and test for the status in flips.test. Occasionally the test runs perfectly, but sometimes it gets stuck.

**Comment by stonier** [comment]
I don't know of any way, but never had the need before. It really shouldn't get stuck though - or at least we should understand why it's getting stuck.

**Pull request merged**
