### PR TITLE
hub_discovery and gateway are now synchronized in what gateways have bee...

### LINKED ISSUE #179: rocon_hub_client and gateways should not independently try and detect when a hub goes down
The gateway does this check [here](https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_gateway/src/rocon_gateway/gateway_hub.py#L71).

The rocon_hub_client does this check [directly pinging the hub](https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_hub_client/src/rocon_hub_client/hub_discovery.py#L120) or [detecting if the address is still available through zeroconf](https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_hub_client/src/rocon_hub_client/hub_discovery.py#L132)

As far as I can see, it is quite possible that the gateway kicks the hub out, but the hub_discovery_client never tries to reestablish a connection once the hub becomes available again.

### PR DESCRIPTION
**Pull request by piyushk**
...n discovered and registered by the gateway. closes #179

### CODE REVIEW

**Comment by piyushk** [comment]
There is 1 catch with this pull request. 

I've had to change the semantics of hub_discovery bothering the gateway in case the gateway does not want to connect to the hub. Let's say that you are configured to connect to a hub through both zeroconf and direct, you'll see repeated warnings about being already connected to the hub.

**Comment by stonier** [comment]
Probably need to work on this one a bit yet. That 1 catch confuses things a bit.

1) It reads strangely that it doesn't add new_services to `self_zeroconf_discovered_hubs` just because it already connected directly. 

2) Very spammy as is.

Both 1) and 2) are cosmetic though. Certainly seems to work ok.

What if we add it to `self._zeroconf_discovered_hubs` on `SUCCESS` or `HUB_CONNECTION_ALREADY_EXISTS`? Does cleanup still happen properly?

**Comment by piyushk** [comment]
@stonier. I'll get back to you on this tomorrow. I know that I managed to produce a failure case when I used `HUB_CONNECTION_ALREADY_EXISTS` as well, but I can't remember it now.

**Comment by stonier** [comment]
ok.

**Comment by piyushk** [comment]
For the record, your solution was fine to solve problems 1) and 2) above.

I am closing this pull request in favor of another one. Will send a different one soon.

**Comment by stonier** [comment]
:+1:

**Pull request closed without merging**
