### PR TITLE
Ping from gateway + Separate Connection Message

### LINKED ISSUE #219: What is correct behaviour for hub-gateway pinger
**Relevant Code**
- [rocon_hub::Pinger](https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_hub/src/rocon_hub/watcher.py#L60)

_Current Funny Behaviour_

Steps to reproduce some funny behaviour
- Run a local gateway and hub
- Remotely run a remote gateway, discovers our hub
- Cut the wireless connection on the remote gateway.
- Kill the remote gateway (i.e. ctrl-c)
- Restart the remote network.

Currently the pinger on the hub will have not deleted the remote gateway information yet (because of the long timeout), and when the network restarts, it will ping with success again and positively list the remote gateway despite the fact that gateway software is no longer running on the remote machine.

_Desired Behaviour_

Should we implement some check after the ping to make sure there is a gateway there?

### PR DESCRIPTION
**Pull request by piyushk**
- Now, the gateway pings the hub (instead of the hub pinging the gateway). closes #219
- Separate ConnectionStatistics message (useful for resuse in rocon_concert)

### CODE REVIEW

**Comment by piyushk** [comment]
Needs to be pulled at the same time as https://github.com/robotics-in-concert/rocon_msgs/pull/50

**Comment by stonier** [comment]
Missed this one, but need it for other development and it looks ok so will merge it now and test in the morning

**Comment by stonier** [comment]
Tested - looks like it's working apart from a small bug I fixed in #224

**Comment by piyushk** [comment]
Awesome. Thanks for testing it.

**Pull request merged**
