### PR TITLE
Spammy discovery hub

### PR DESCRIPTION
**Pull request by jihoonl**
Fixs #286

### CODE REVIEW

**Comment by stonier** [comment]
I notice you removed the check for 'reasons_not_to_keep_scanning' with just an else... there isn't any reason in there that is going to slip through into that else that was blocked before?

**Comment by stonier** [comment]
i.e. specifically wondering if there are other error codes outside of

```
ErrorCodes.SUCCESS,
ErrorCodes.HUB_CONNECTION_ALREADY_EXISTS,
ErrorCodes.HUB_CONNECTION_NOT_IN_NONEMPTY_WHITELIST,
ErrorCodes.HUB_CONNECTION_UNRESOLVABLE
```

that should be handled differently.

**Comment by stonier** [comment]
Otherwise looks good.

**Comment by jihoonl** [comment]
Re above question - we still use the same error code array, and there are no error codes outside of these (base assumption is that all others are bad)(

**Pull request merged**
